import {
  cancelFaceDetection_h,
  createFaceIdentity,
  deleteFaceIdentity,
  getDetectionProgress,
  getFaceIdentity,
  getScanScope,
  listFaceIdentities,
  mergeIdentities,
  recluster,
  removeFaceFromIdentity,
  resetFaceData,
  setScanScope,
  startFaceDetection,
  updateFaceIdentity,
} from "./handlers";

export const faces = {
  cancelFaceDetection: cancelFaceDetection_h,
  createFaceIdentity,
  deleteFaceIdentity,
  getDetectionProgress,
  getFaceIdentity,
  getScanScope,
  listFaceIdentities,
  mergeIdentities,
  recluster,
  removeFaceFromIdentity,
  resetFaceData,
  setScanScope,
  startFaceDetection,
  updateFaceIdentity,
};
