import {
  cancelFaceDetection_h,
  confirmFace,
  createFaceIdentity,
  deleteFaceIdentity,
  getDetectionProgress,
  getFaceIdentity,
  getScanScope,
  hideFaceIdentity,
  listFaceCandidates,
  listFaceIdentities,
  listFaceReviewQueue,
  listHiddenFaceIdentities,
  listPhotoFaces,
  mergeIdentities,
  recluster,
  removeFaceFromIdentity,
  resetFaceData,
  restoreFaceToIdentity,
  restoreHiddenFaceIdentity,
  restoreRejectedFace,
  reviewFace,
  setScanScope,
  startFaceDetection,
  updateFaceIdentity,
} from "./handlers";

export const faces = {
  cancelFaceDetection: cancelFaceDetection_h,
  confirmFace,
  createFaceIdentity,
  deleteFaceIdentity,
  getDetectionProgress,
  getFaceIdentity,
  getScanScope,
  hideFaceIdentity,
  listFaceIdentities,
  listHiddenFaceIdentities,
  mergeIdentities,
  recluster,
  removeFaceFromIdentity,
  restoreHiddenFaceIdentity,
  restoreFaceToIdentity,
  resetFaceData,
  restoreRejectedFace,
  reviewFace,
  setScanScope,
  startFaceDetection,
  updateFaceIdentity,
  listFaceCandidates,
  listFaceReviewQueue,
  listPhotoFaces,
};
