import {
  addPhotosToSession,
  batchUpdatePhotoStatus,
  completeSession,
  createSession,
  deleteSession,
  getNextPair,
  getSession,
  listSessions,
  recordSkip,
  skipSimilarPhotos,
  submitComparison,
  undoLastAction,
  updatePhotoStatus,
} from "./handlers";

export const cull = {
  addPhotosToSession,
  batchUpdatePhotoStatus,
  completeSession,
  createSession,
  deleteSession,
  getNextPair,
  getSession,
  listSessions,
  recordSkip,
  skipSimilarPhotos,
  submitComparison,
  undoLastAction,
  updatePhotoStatus,
};
