import {
  batchGenerateTags,
  cancelAiIndexing,
  getAiHealth,
  getAiProgress,
  getAiStatus,
  pauseAiIndexing,
  resetAiIndex,
  resumeAiIndexing,
  startAiIndexing,
  stopAiIndexing,
} from "./handlers/ai";
import {
  exportPhotos,
  getWatermarkSettings,
  setWatermarkSettings,
} from "./handlers/export";
import {
  cancelAllImports_h,
  cancelQueuedImports_h,
  deleteFolder,
  getFolders,
  getImportQueueStatus_h,
  getPhotoDetail,
  getPhotoExif,
  listPhotos,
  scanFolder,
  stopScanning,
  updateFolderAppearance,
} from "./handlers/listing";
import {
  backfillMissingThumbnails,
  cleanDuplicateGroups,
  cleanOrphanThumbnails,
  cleanupOrphanPhotos,
  clearThumbCache,
  convertPhotos,
  deletePhoto,
  deletePhotos,
  emptyTrash,
  listDeletedPhotos,
  movePhotos,
  permanentlyDeletePhotos,
  previewRename,
  renamePhotos,
  restorePhotos,
  scanOrphanThumbnails,
  toggleFavorite,
} from "./handlers/mutations";
import {
  searchByImage,
  searchByText,
  searchCompound,
  searchSpotlight,
} from "./handlers/search";
import { generateAndUploadShare } from "./handlers/share";
import {
  dismissDuplicate,
  dismissDuplicates,
  findDuplicates,
  getColorDistribution,
  getDuplicateStats,
  getExifCandidates,
  getGeoLocations,
  getIndexStats,
  getStats,
  migrateColors,
} from "./handlers/stats";
import {
  addTag,
  confirmPhotoTag,
  deleteTag,
  getPhotoTagAnalysisStatus,
  getPhotoTags,
  getTags,
  removePhotoTag,
  setPhotoTag,
  suggestTags,
} from "./handlers/tags";

export const photos = {
  addTag,
  backfillMissingThumbnails,
  batchGenerateTags,
  cancelAiIndexing,
  cancelAllImports: cancelAllImports_h,
  cancelQueuedImports: cancelQueuedImports_h,
  cleanupOrphanPhotos,
  cleanDuplicateGroups,
  cleanOrphanThumbnails,
  clearThumbCache,
  confirmPhotoTag,
  convertPhotos,
  deleteFolder,
  deletePhoto,
  deletePhotos,
  deleteTag,
  dismissDuplicate,
  dismissDuplicates,
  emptyTrash,
  exportPhotos,
  findDuplicates,
  getAiHealth,
  getAiProgress,
  getAiStatus,
  getColorDistribution,
  getDuplicateStats,
  getExifCandidates,
  getFolders,
  getGeoLocations,
  getImportQueueStatus: getImportQueueStatus_h,
  getIndexStats,
  getPhotoDetail,
  getPhotoExif,
  getPhotoTags,
  getPhotoTagAnalysisStatus,
  getStats,
  getTags,
  getWatermarkSettings,
  listDeletedPhotos,
  listPhotos,
  migrateColors,
  movePhotos,
  pauseAiIndexing,
  permanentlyDeletePhotos,
  previewRename,
  removePhotoTag,
  renamePhotos,
  resetAiIndex,
  restorePhotos,
  resumeAiIndexing,
  scanFolder,
  scanOrphanThumbnails,
  searchByImage,
  searchByText,
  searchCompound,
  searchSpotlight,
  setPhotoTag,
  setWatermarkSettings,
  startAiIndexing,
  stopAiIndexing,
  stopScanning,
  suggestTags,
  toggleFavorite,
  updateFolderAppearance,
  generateAndUploadShare,
};
