import {
  getAdvancedExifStatus,
  pauseAdvancedExif,
  resumeAdvancedExif,
  retryAdvancedExif,
  startAdvancedExif,
} from "./handlers/advanced-exif";
import {
  batchGenerateTags,
  cancelAiIndexing,
  getAiHealth,
  getAiProgress,
  getAiStatus,
  pauseAiIndexing,
  resetAiIndex,
  resumeAiIndexing,
  startAiIndexing,
  stopAiIndexing,
} from "./handlers/ai";
import {
  createDuplicateCleanupPlanHandler,
  executeDuplicateCleanupPlanHandler,
  listDuplicateCleanupBatchesHandler,
  restoreDuplicateCleanupBatchHandler,
} from "./handlers/duplicate-cleanup";
import {
  applyDuplicateKeepCountHandler,
  updateDuplicateReview,
} from "./handlers/duplicate-review";
import {
  exportPhotos,
  getWatermarkSettings,
  setWatermarkSettings,
} from "./handlers/export";
import {
  cancelAllImports_h,
  cancelQueuedImports_h,
  deleteFolder,
  getFolders,
  getImportQueueStatus_h,
  getPhotoDetail,
  getPhotoExif,
  listPhotos,
  scanFolder,
  stopScanning,
  updateFolderAppearance,
} from "./handlers/listing";
import {
  backfillMissingThumbnails,
  cleanDuplicateGroups,
  cleanOrphanThumbnails,
  cleanupOrphanPhotos,
  clearThumbCache,
  convertPhotos,
  deletePhoto,
  deletePhotos,
  emptyTrash,
  listDeletedPhotos,
  movePhotos,
  permanentlyDeletePhotos,
  previewRename,
  renamePhotos,
  restorePhotos,
  scanOrphanThumbnails,
  toggleFavorite,
} from "./handlers/mutations";
import {
  getImageSearchPreview,
  searchByImage,
  searchByText,
  searchCompound,
  searchSpotlight,
} from "./handlers/search";
import {
  clearSequenceExclusions,
  createSequence,
  deleteManualSequence,
  dissolveAndExcludeSequence,
  dissolveSequence,
  getSequence,
  ignoreSequencePhotos,
  keepSequencePhotos,
  listSequenceSuggestions,
  listSequences,
  mergeSequences,
  rebuildSequences,
  recommendSequenceRepresentative,
  removeSequenceMembers,
  restoreAutomaticSequence,
  setSequenceRepresentative,
  splitSequence,
  updateSequenceMembers,
} from "./handlers/sequences";
import { generateAndUploadShare } from "./handlers/share";
import {
  cancelDuplicateScanHandler,
  dismissDuplicate,
  dismissDuplicates,
  findDuplicates,
  getColorDistribution,
  getDuplicateGroupPhotos,
  getDuplicateScan,
  getDuplicateScanProgressHandler,
  getDuplicateStats,
  getExifCandidates,
  getGeoLocations,
  getIndexStats,
  getStats,
  migrateColors,
} from "./handlers/stats";
import {
  addTag,
  confirmPhotoTag,
  deleteTag,
  getPhotoTagAnalysisStatus,
  getPhotoTags,
  getTags,
  removePhotoTag,
  setPhotoTag,
  suggestTags,
} from "./handlers/tags";

export const photos = {
  applyDuplicateKeepCount: applyDuplicateKeepCountHandler,
  addTag,
  backfillMissingThumbnails,
  batchGenerateTags,
  cancelAiIndexing,
  cancelAllImports: cancelAllImports_h,
  cancelQueuedImports: cancelQueuedImports_h,
  cleanupOrphanPhotos,
  cleanDuplicateGroups,
  createDuplicateCleanupPlan: createDuplicateCleanupPlanHandler,
  cleanOrphanThumbnails,
  clearThumbCache,
  confirmPhotoTag,
  convertPhotos,
  deleteFolder,
  deletePhoto,
  deletePhotos,
  deleteTag,
  dismissDuplicate,
  dismissDuplicates,
  emptyTrash,
  executeDuplicateCleanupPlan: executeDuplicateCleanupPlanHandler,
  exportPhotos,
  findDuplicates,
  startDuplicateScan: findDuplicates,
  cancelDuplicateScan: cancelDuplicateScanHandler,
  getDuplicateScanProgress: getDuplicateScanProgressHandler,
  listDuplicateCleanupBatches: listDuplicateCleanupBatchesHandler,
  getDuplicateGroupPhotos,
  getDuplicateScan,
  getAiHealth,
  getAiProgress,
  getAiStatus,
  getAdvancedExifStatus,
  getColorDistribution,
  getDuplicateStats,
  getExifCandidates,
  getFolders,
  getGeoLocations,
  getImportQueueStatus: getImportQueueStatus_h,
  getImageSearchPreview,
  getIndexStats,
  getPhotoDetail,
  getPhotoExif,
  getPhotoTags,
  getPhotoTagAnalysisStatus,
  getStats,
  getTags,
  getWatermarkSettings,
  getSequence,
  deleteManualSequence,
  clearSequenceExclusions,
  dissolveSequence,
  dissolveAndExcludeSequence,
  listDeletedPhotos,
  listPhotos,
  listSequenceSuggestions,
  listSequences,
  mergeSequences,
  keepSequencePhotos,
  migrateColors,
  createSequence,
  ignoreSequencePhotos,
  rebuildSequences,
  recommendSequenceRepresentative,
  removeSequenceMembers,
  restoreAutomaticSequence,
  movePhotos,
  pauseAiIndexing,
  pauseAdvancedExif,
  permanentlyDeletePhotos,
  previewRename,
  removePhotoTag,
  renamePhotos,
  resetAiIndex,
  restorePhotos,
  restoreDuplicateCleanupBatch: restoreDuplicateCleanupBatchHandler,
  resumeAiIndexing,
  resumeAdvancedExif,
  retryAdvancedExif,
  scanFolder,
  scanOrphanThumbnails,
  searchByImage,
  searchByText,
  searchCompound,
  searchSpotlight,
  setPhotoTag,
  setSequenceRepresentative,
  setWatermarkSettings,
  startAiIndexing,
  startAdvancedExif,
  stopAiIndexing,
  stopScanning,
  suggestTags,
  splitSequence,
  toggleFavorite,
  updateDuplicateReview,
  updateFolderAppearance,
  updateSequenceMembers,
  generateAndUploadShare,
};
