const TAG_DISPLAY_EN: Record<string, string> = {
  场景: "Scene",
  人物: "People",
  动物: "Animal",
  物体: "Object",
  活动: "Activity",
  光影: "Lighting",
  风格: "Style",
  色彩: "Color",
  天气: "Weather",

  室内: "Indoor",
  户外: "Outdoor",
  城市: "City",
  乡村: "Countryside",
  自然风景: "Nature",
  海滩: "Beach",
  山脉: "Mountain",
  森林: "Forest",
  街道: "Street",
  建筑: "Architecture",
  花园: "Garden",
  田野: "Field",
  湖泊: "Lake",
  河流: "River",
  沙漠: "Desert",
  雪景: "Snowscape",
  天空: "Sky",
  夜景: "Night Scene",
  水下: "Underwater",
  机场: "Airport",
  车站: "Train Station",
  市场: "Market",
  餐厅: "Restaurant",
  办公室: "Office",
  教室: "Classroom",
  花海: "Flower Field",

  人像: "Portrait",
  群体: "Group",
  儿童: "Child",
  婴儿: "Baby",
  情侣: "Couple",
  家庭: "Family",
  女性: "Woman",
  男性: "Man",
  老人: "Elderly",
  自拍: "Selfie",
  背影: "Back View",
  笑容: "Smile",
  婚礼: "Wedding",
  手部特写: "Hands",

  猫咪: "Cat",
  狗狗: "Dog",
  鸟类: "Bird",
  鱼类: "Fish",
  昆虫: "Insect",
  马: "Horse",
  兔子: "Rabbit",
  鹿: "Deer",
  熊猫: "Panda",
  松鼠: "Squirrel",
  宠物: "Pet",
  野生动物: "Wildlife",

  食物: "Food",
  甜点: "Dessert",
  咖啡: "Coffee",
  花卉: "Flower",
  树木: "Tree",
  汽车: "Car",
  自行车: "Bicycle",
  船: "Boat",
  飞机: "Airplane",
  书籍: "Book",
  手机: "Phone",
  电脑: "Computer",
  相机: "Camera",
  眼镜: "Glasses",
  帽子: "Hat",
  包: "Bag",
  雨伞: "Umbrella",
  蜡烛: "Candle",
  镜子: "Mirror",
  钟表: "Clock",

  运动: "Sports",
  跑步: "Running",
  游泳: "Swimming",
  徒步: "Hiking",
  骑行: "Cycling",
  舞蹈: "Dancing",
  烹饪: "Cooking",
  阅读: "Reading",
  音乐: "Music",
  绘画: "Painting",
  旅行: "Travel",
  露营: "Camping",
  聚会: "Party",
  购物: "Shopping",
  瑜伽: "Yoga",

  白天: "Daytime",
  夜晚: "Night",
  日落: "Sunset",
  日出: "Sunrise",
  逆光: "Backlight",
  阴天: "Overcast",
  雾气: "Fog",
  霓虹灯: "Neon",
  烛光: "Candlelight",
  彩虹: "Rainbow",

  黑白: "Black & White",
  鲜艳: "Vivid",
  暗调: "Dark Tone",
  亮调: "Bright Tone",
  微距: "Macro",
  虚化背景: "Bokeh",
  全景: "Panorama",
  航拍: "Aerial",
  长曝光: "Long Exposure",
  倒影: "Reflection",
  剪影: "Silhouette",
  复古: "Vintage",
  极简: "Minimalist",
  对称: "Symmetry",
  抽象: "Abstract",
  多重曝光: "Double Exposure",
  平铺: "Flat Lay",
  街拍: "Street Photography",

  红色调: "Red",
  蓝色调: "Blue",
  绿色调: "Green",
  黄色调: "Yellow",
  白色调: "White",
  黑色调: "Black",
  紫色调: "Purple",
  橙色调: "Orange",
  粉色调: "Pink",
  金色调: "Gold",

  雨天: "Rainy",
  雪天: "Snowy",
  雾天: "Foggy",
  风天: "Windy",
  晴朗: "Sunny",
  多云: "Cloudy",
};

export function getTagDisplayName(name: string, language: string): string {
  if (!name) {
    return name;
  }
  if (language.startsWith("zh")) {
    return name;
  }
  return TAG_DISPLAY_EN[name] ?? name;
}
