import {
  commitInstall,
  discardInspection,
  inspectFromDialog,
  installFromDialog,
  listPlugins,
  loadDevDirectoryFromDialog,
  reloadDevPlugin,
  removeDevPlugin,
  removePluginAsset,
  reportPluginActivationResult,
  resetPluginSettings,
  selectPluginAsset,
  setPluginDeveloperMode,
  setPluginEnabled,
  setPluginSettings,
  uninstallPlugin,
} from "./handlers";

export const plugins = {
  list: listPlugins,
  installFromDialog,
  inspectFromDialog,
  commitInstall,
  discardInspection,
  reportActivationResult: reportPluginActivationResult,
  setEnabled: setPluginEnabled,
  setSettings: setPluginSettings,
  selectAsset: selectPluginAsset,
  removeAsset: removePluginAsset,
  resetSettings: resetPluginSettings,
  uninstall: uninstallPlugin,
  setDeveloperMode: setPluginDeveloperMode,
  loadDevDirectoryFromDialog,
  reloadDevPlugin,
  removeDevPlugin,
};
