/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleIdentityIdRouteImport } from './routes/people.$identityId'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums.$albumId'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdentityIdRoute = PeopleIdentityIdRouteImport.update({
  id: '/$identityId',
  path: '/$identityId',
  getParentRoute: () => PeopleRoute,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => AlbumsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/people/$identityId': typeof PeopleIdentityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/people/$identityId': typeof PeopleIdentityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/people/$identityId': typeof PeopleIdentityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/dashboard'
    | '/duplicates'
    | '/people'
    | '/settings'
    | '/trash'
    | '/albums/$albumId'
    | '/people/$identityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/dashboard'
    | '/duplicates'
    | '/people'
    | '/settings'
    | '/trash'
    | '/albums/$albumId'
    | '/people/$identityId'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/dashboard'
    | '/duplicates'
    | '/people'
    | '/settings'
    | '/trash'
    | '/albums/$albumId'
    | '/people/$identityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DuplicatesRoute: typeof DuplicatesRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TrashRoute: typeof TrashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$identityId': {
      id: '/people/$identityId'
      path: '/$identityId'
      fullPath: '/people/$identityId'
      preLoaderRoute: typeof PeopleIdentityIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof AlbumsRoute
    }
  }
}

interface AlbumsRouteChildren {
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
}

const AlbumsRouteChildren: AlbumsRouteChildren = {
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
}

const AlbumsRouteWithChildren =
  AlbumsRoute._addFileChildren(AlbumsRouteChildren)

interface PeopleRouteChildren {
  PeopleIdentityIdRoute: typeof PeopleIdentityIdRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleIdentityIdRoute: PeopleIdentityIdRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DuplicatesRoute: DuplicatesRoute,
  PeopleRoute: PeopleRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TrashRoute: TrashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
