/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CullRouteImport } from './routes/cull'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsWatermarkRouteImport } from './routes/settings.watermark'
import { Route as SettingsUpdateRouteImport } from './routes/settings.update'
import { Route as SettingsStorageRouteImport } from './routes/settings.storage'
import { Route as SettingsCloudSyncRouteImport } from './routes/settings.cloud-sync'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAccelerationRouteImport } from './routes/settings.acceleration'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as PeopleIdentityIdRouteImport } from './routes/people.$identityId'
import { Route as CullSessionIdRouteImport } from './routes/cull.$sessionId'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums.$albumId'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CullRoute = CullRouteImport.update({
  id: '/cull',
  path: '/cull',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWatermarkRoute = SettingsWatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUpdateRoute = SettingsUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCloudSyncRoute = SettingsCloudSyncRouteImport.update({
  id: '/cloud-sync',
  path: '/cloud-sync',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccelerationRoute = SettingsAccelerationRouteImport.update({
  id: '/acceleration',
  path: '/acceleration',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const PeopleIdentityIdRoute = PeopleIdentityIdRouteImport.update({
  id: '/$identityId',
  path: '/$identityId',
  getParentRoute: () => PeopleRoute,
} as any)
const CullSessionIdRoute = CullSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => CullRoute,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => AlbumsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/cull': typeof CullRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/trash': typeof TrashRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/cull/$sessionId': typeof CullSessionIdRoute
  '/people/$identityId': typeof PeopleIdentityIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/acceleration': typeof SettingsAccelerationRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/cloud-sync': typeof SettingsCloudSyncRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/update': typeof SettingsUpdateRoute
  '/settings/watermark': typeof SettingsWatermarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/cull': typeof CullRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/trash': typeof TrashRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/cull/$sessionId': typeof CullSessionIdRoute
  '/people/$identityId': typeof PeopleIdentityIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/acceleration': typeof SettingsAccelerationRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/cloud-sync': typeof SettingsCloudSyncRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/update': typeof SettingsUpdateRoute
  '/settings/watermark': typeof SettingsWatermarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/cull': typeof CullRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/trash': typeof TrashRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/cull/$sessionId': typeof CullSessionIdRoute
  '/people/$identityId': typeof PeopleIdentityIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/acceleration': typeof SettingsAccelerationRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/cloud-sync': typeof SettingsCloudSyncRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/update': typeof SettingsUpdateRoute
  '/settings/watermark': typeof SettingsWatermarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/cull'
    | '/dashboard'
    | '/duplicates'
    | '/people'
    | '/settings'
    | '/trash'
    | '/albums/$albumId'
    | '/cull/$sessionId'
    | '/people/$identityId'
    | '/settings/about'
    | '/settings/acceleration'
    | '/settings/appearance'
    | '/settings/cloud-sync'
    | '/settings/storage'
    | '/settings/update'
    | '/settings/watermark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/cull'
    | '/dashboard'
    | '/duplicates'
    | '/people'
    | '/settings'
    | '/trash'
    | '/albums/$albumId'
    | '/cull/$sessionId'
    | '/people/$identityId'
    | '/settings/about'
    | '/settings/acceleration'
    | '/settings/appearance'
    | '/settings/cloud-sync'
    | '/settings/storage'
    | '/settings/update'
    | '/settings/watermark'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/cull'
    | '/dashboard'
    | '/duplicates'
    | '/people'
    | '/settings'
    | '/trash'
    | '/albums/$albumId'
    | '/cull/$sessionId'
    | '/people/$identityId'
    | '/settings/about'
    | '/settings/acceleration'
    | '/settings/appearance'
    | '/settings/cloud-sync'
    | '/settings/storage'
    | '/settings/update'
    | '/settings/watermark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRouteWithChildren
  CullRoute: typeof CullRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DuplicatesRoute: typeof DuplicatesRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  TrashRoute: typeof TrashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cull': {
      id: '/cull'
      path: '/cull'
      fullPath: '/cull'
      preLoaderRoute: typeof CullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/watermark': {
      id: '/settings/watermark'
      path: '/watermark'
      fullPath: '/settings/watermark'
      preLoaderRoute: typeof SettingsWatermarkRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/update': {
      id: '/settings/update'
      path: '/update'
      fullPath: '/settings/update'
      preLoaderRoute: typeof SettingsUpdateRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/cloud-sync': {
      id: '/settings/cloud-sync'
      path: '/cloud-sync'
      fullPath: '/settings/cloud-sync'
      preLoaderRoute: typeof SettingsCloudSyncRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/acceleration': {
      id: '/settings/acceleration'
      path: '/acceleration'
      fullPath: '/settings/acceleration'
      preLoaderRoute: typeof SettingsAccelerationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/people/$identityId': {
      id: '/people/$identityId'
      path: '/$identityId'
      fullPath: '/people/$identityId'
      preLoaderRoute: typeof PeopleIdentityIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/cull/$sessionId': {
      id: '/cull/$sessionId'
      path: '/$sessionId'
      fullPath: '/cull/$sessionId'
      preLoaderRoute: typeof CullSessionIdRouteImport
      parentRoute: typeof CullRoute
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof AlbumsRoute
    }
  }
}

interface AlbumsRouteChildren {
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
}

const AlbumsRouteChildren: AlbumsRouteChildren = {
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
}

const AlbumsRouteWithChildren =
  AlbumsRoute._addFileChildren(AlbumsRouteChildren)

interface CullRouteChildren {
  CullSessionIdRoute: typeof CullSessionIdRoute
}

const CullRouteChildren: CullRouteChildren = {
  CullSessionIdRoute: CullSessionIdRoute,
}

const CullRouteWithChildren = CullRoute._addFileChildren(CullRouteChildren)

interface PeopleRouteChildren {
  PeopleIdentityIdRoute: typeof PeopleIdentityIdRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleIdentityIdRoute: PeopleIdentityIdRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAccelerationRoute: typeof SettingsAccelerationRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsCloudSyncRoute: typeof SettingsCloudSyncRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsUpdateRoute: typeof SettingsUpdateRoute
  SettingsWatermarkRoute: typeof SettingsWatermarkRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAccelerationRoute: SettingsAccelerationRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsCloudSyncRoute: SettingsCloudSyncRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsUpdateRoute: SettingsUpdateRoute,
  SettingsWatermarkRoute: SettingsWatermarkRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRouteWithChildren,
  CullRoute: CullRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DuplicatesRoute: DuplicatesRoute,
  PeopleRoute: PeopleRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  TrashRoute: TrashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
