// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

declare module "*.css";

declare module "*.png";

interface Window {
  electronAPI: {
    getFilePath: (file: File) => string;
    preloadReady: boolean;
    /** HTTP 服务器端口（由主进程在 createWindow 时通过 --http-port 参数同步注入） */
    httpPort: number;
    startDrag: (filePath: string) => void;
    copyImageToClipboard: (filePath: string) => Promise<boolean>;
    restartApp: () => void;
    installUpdate: () => void;
    setLanguage: (lang: string) => void;
    openExternal: (url: string) => void;
    app: {
      getHttpPort: () => Promise<number | null>;
    };
  };
}
