// Chinese -> English search keyword mapping with semantic categories.
// CLIP ViT-B/32 was trained on English image-text pairs, so Chinese queries
// produce poor alignment. We translate known Chinese terms to English before
// embedding to improve search accuracy.

export type DictCategory =
  | "subject"
  | "scene"
  | "time"
  | "style"
  | "activity"
  | "color"
  | "weather"
  | "object";

export interface DictEntry {
  category: DictCategory;
  en: string;
}

export const ZH_TO_EN_SEARCH: Record<string, DictEntry> = {
  // === SUBJECTS — People ===
  人: { en: "person people human", category: "subject" },
  人物: { en: "person people human portrait", category: "subject" },
  人像: { en: "portrait person face close-up", category: "subject" },
  女孩: { en: "girl young woman female person", category: "subject" },
  男孩: { en: "boy young man male person", category: "subject" },
  女人: { en: "woman female adult person", category: "subject" },
  男人: { en: "man male adult person", category: "subject" },
  孩子: { en: "child kid young person", category: "subject" },
  儿童: { en: "child kid young person", category: "subject" },
  婴儿: { en: "baby infant newborn person", category: "subject" },
  宝宝: { en: "baby infant cute child", category: "subject" },
  老人: { en: "elderly senior old person", category: "subject" },
  情侣: { en: "couple romantic pair people love", category: "subject" },
  家庭: { en: "family parents children group people", category: "subject" },
  朋友: { en: "friends group people together", category: "subject" },
  背影: { en: "back silhouette person behind", category: "subject" },
  笑容: { en: "smile happy laughing joyful face", category: "subject" },
  自拍: { en: "selfie person face camera phone portrait", category: "subject" },
  新娘: { en: "bride wedding dress woman", category: "subject" },
  新郎: { en: "groom wedding suit man", category: "subject" },
  婚礼: { en: "wedding ceremony bride groom celebration", category: "subject" },
  // === SUBJECTS — Animals ===
  猫: { en: "cat kitten feline", category: "subject" },
  猫咪: { en: "cat kitten feline", category: "subject" },
  狗: { en: "dog puppy canine", category: "subject" },
  狗狗: { en: "dog puppy canine", category: "subject" },
  鸟: { en: "bird flying feathers", category: "subject" },
  鸟类: { en: "bird flying feathers", category: "subject" },
  鱼: { en: "fish underwater aquarium", category: "subject" },
  昆虫: { en: "insect bug butterfly bee macro", category: "subject" },
  蝴蝶: { en: "butterfly insect colorful wings nature", category: "subject" },
  蜜蜂: { en: "bee insect honey flower macro", category: "subject" },
  蜻蜓: { en: "dragonfly insect wings macro nature", category: "subject" },
  蚂蚁: { en: "ant insect small ground macro", category: "subject" },
  动物: { en: "animal wildlife", category: "subject" },
  马: { en: "horse animal running field", category: "subject" },
  牛: { en: "cow cattle animal farm", category: "subject" },
  羊: { en: "sheep lamb animal wool farm", category: "subject" },
  兔子: { en: "rabbit bunny animal pet", category: "subject" },
  熊猫: { en: "panda bear animal black white", category: "subject" },
  老虎: { en: "tiger animal wild cat predator", category: "subject" },
  狮子: { en: "lion animal wild cat predator", category: "subject" },
  大象: { en: "elephant animal large wild", category: "subject" },
  猴子: { en: "monkey animal primate wild", category: "subject" },
  鹿: { en: "deer animal wildlife forest antler", category: "subject" },
  狐狸: { en: "fox animal wild orange predator", category: "subject" },
  松鼠: { en: "squirrel animal rodent tree forest", category: "subject" },
  蛇: { en: "snake reptile animal wild", category: "subject" },
  鸽子: { en: "pigeon dove bird white grey urban", category: "subject" },
  猫头鹰: { en: "owl bird nocturnal predator", category: "subject" },
  老鹰: { en: "eagle hawk bird predator sky wildlife", category: "subject" },
  // === SCENES ===
  室内: { en: "indoor room inside interior", category: "scene" },
  户外: { en: "outdoor outside", category: "scene" },
  城市: { en: "city urban street downtown", category: "scene" },
  乡村: { en: "countryside rural village", category: "scene" },
  海: { en: "ocean sea beach water", category: "scene" },
  海边: { en: "beach ocean sea shore seaside", category: "scene" },
  海滩: { en: "beach sand ocean shore", category: "scene" },
  沙滩: { en: "beach sand shore seaside", category: "scene" },
  山: { en: "mountain hill peak", category: "scene" },
  山脉: { en: "mountain hill range", category: "scene" },
  高山: { en: "tall mountain peak summit", category: "scene" },
  树: { en: "tree plant forest", category: "scene" },
  树木: { en: "tree plant forest", category: "scene" },
  森林: { en: "forest woods trees nature dense", category: "scene" },
  天空: { en: "sky clouds atmosphere", category: "scene" },
  云: { en: "clouds sky", category: "scene" },
  街道: { en: "street road urban", category: "scene" },
  路: { en: "road street path", category: "scene" },
  建筑: { en: "building architecture facade", category: "scene" },
  花园: { en: "garden flowers park", category: "scene" },
  公园: { en: "park garden green nature outdoor", category: "scene" },
  草地: { en: "grass field meadow green", category: "scene" },
  田野: { en: "field meadow grass countryside", category: "scene" },
  草原: { en: "grassland prairie field vast nature", category: "scene" },
  湖: { en: "lake water reflection calm", category: "scene" },
  湖泊: { en: "lake water reflection calm", category: "scene" },
  河: { en: "river stream water flowing", category: "scene" },
  河流: { en: "river stream water flowing", category: "scene" },
  小溪: { en: "stream creek water small", category: "scene" },
  瀑布: { en: "waterfall water cascade", category: "scene" },
  水: { en: "water lake river ocean", category: "scene" },
  水面: { en: "water surface reflection", category: "scene" },
  大海: { en: "ocean sea blue water vast", category: "scene" },
  沙漠: { en: "desert sand dry arid nature", category: "scene" },
  悬崖: { en: "cliff rock steep nature ocean", category: "scene" },
  峡谷: { en: "canyon valley gorge rock nature", category: "scene" },
  火山: { en: "volcano mountain lava eruption", category: "scene" },
  冰山: { en: "iceberg ice snow cold ocean polar", category: "scene" },
  桥: { en: "bridge crossing water architecture", category: "scene" },
  码头: { en: "dock pier harbor water boat", category: "scene" },
  灯塔: { en: "lighthouse tower light ocean coast", category: "scene" },
  教堂: { en: "church cathedral building architecture", category: "scene" },
  寺庙: { en: "temple building architecture religious", category: "scene" },
  城堡: { en: "castle building architecture historic", category: "scene" },
  塔: { en: "tower tall building structure", category: "scene" },
  市场: { en: "market shopping bazaar stall people", category: "scene" },
  餐厅: { en: "restaurant dining food table indoor", category: "scene" },
  咖啡馆: { en: "cafe coffee shop indoor cozy", category: "scene" },
  厨房: { en: "kitchen cooking room indoor food", category: "scene" },
  卧室: { en: "bedroom bed sleeping room indoor", category: "scene" },
  办公室: { en: "office desk workspace computer indoor", category: "scene" },
  教室: { en: "classroom school education indoor", category: "scene" },
  图书馆: { en: "library books reading indoor quiet", category: "scene" },
  医院: { en: "hospital medical building indoor", category: "scene" },
  学校: { en: "school education building campus", category: "scene" },
  超市: { en: "supermarket shopping store indoor", category: "scene" },
  地铁: { en: "subway metro underground train station", category: "scene" },
  机场: { en: "airport airplane terminal travel", category: "scene" },
  车站: { en: "train station railway platform", category: "scene" },
  隧道: { en: "tunnel underground passage dark", category: "scene" },
  // === OBJECTS ===
  花: { en: "flower blossom petal", category: "object" },
  花卉: { en: "flower blossom petal", category: "object" },
  车: { en: "car vehicle automobile", category: "object" },
  汽车: { en: "car vehicle automobile", category: "object" },
  自行车: { en: "bicycle bike cycling", category: "object" },
  摩托车: { en: "motorcycle bike", category: "object" },
  飞机: { en: "airplane aircraft sky flying", category: "object" },
  船: { en: "boat ship water sailing", category: "object" },
  火车: { en: "train railway transportation", category: "object" },
  食物: { en: "food meal dish plate", category: "object" },
  美食: { en: "food meal dish delicious", category: "object" },
  蛋糕: { en: "cake dessert sweet pastry", category: "object" },
  面包: { en: "bread bakery food", category: "object" },
  水果: { en: "fruit fresh colorful", category: "object" },
  草莓: { en: "strawberry fruit red", category: "object" },
  蔬菜: { en: "vegetable green fresh", category: "object" },
  咖啡: { en: "coffee cup drink cafe", category: "object" },
  饮料: { en: "drink beverage glass", category: "object" },
  书: { en: "book reading pages", category: "object" },
  书籍: { en: "book reading pages text", category: "object" },
  手机: { en: "phone smartphone screen mobile", category: "object" },
  电脑: { en: "computer laptop keyboard screen", category: "object" },
  相机: { en: "camera lens photography equipment", category: "object" },
  眼镜: { en: "glasses eyewear spectacles", category: "object" },
  帽子: { en: "hat cap headwear", category: "object" },
  鞋子: { en: "shoes footwear sneakers", category: "object" },
  衣服: { en: "clothing outfit dress garment", category: "object" },
  包: { en: "bag handbag backpack purse", category: "object" },
  雨伞: { en: "umbrella rain protection", category: "object" },
  灯: { en: "lamp light lighting illumination", category: "object" },
  蜡烛: { en: "candle flame light warm", category: "object" },
  玩具: { en: "toy doll plaything child", category: "object" },
  乐器: { en: "musical instrument guitar piano", category: "object" },
  吉他: { en: "guitar musical instrument string", category: "object" },
  钢琴: { en: "piano keyboard musical instrument", category: "object" },
  门: { en: "door entrance gateway", category: "object" },
  窗: { en: "window glass frame", category: "object" },
  窗户: { en: "window glass building", category: "object" },
  桌子: { en: "table desk furniture", category: "object" },
  椅子: { en: "chair furniture seating", category: "object" },
  镜子: { en: "mirror reflection glass", category: "object" },
  钟表: { en: "clock watch time", category: "object" },
  气球: { en: "balloon colorful celebration party", category: "object" },
  礼物: { en: "gift present box package", category: "object" },
  旗帜: { en: "flag banner symbol wind", category: "object" },
  灯笼: { en: "lantern light decoration red festive", category: "object" },
  雕塑: { en: "sculpture statue art monument", category: "object" },
  喷泉: { en: "fountain water spray garden", category: "object" },
  风车: { en: "windmill wind turbine tower", category: "object" },
  热气球: { en: "hot air balloon sky colorful", category: "object" },
  铁轨: { en: "railroad railway train track", category: "object" },
  麦田: { en: "wheat field grain crop golden", category: "object" },
  // === TIME ===
  秋天: { en: "autumn fall season", category: "time" },
  春天: { en: "spring season bloom", category: "time" },
  夏天: { en: "summer season warm", category: "time" },
  冬天: { en: "winter snow season cold", category: "time" },
  去年: { en: "last year", category: "time" },
  今年: { en: "this year", category: "time" },
  上周: { en: "last week", category: "time" },
  昨天: { en: "yesterday", category: "time" },
  早上: { en: "morning sunrise dawn early", category: "time" },
  中午: { en: "noon midday bright", category: "time" },
  下午: { en: "afternoon", category: "time" },
  傍晚: { en: "evening dusk twilight", category: "time" },
  深夜: { en: "late night dark midnight", category: "time" },
  夜晚: { en: "night dark nighttime", category: "time" },
  夜景: { en: "night scene dark city lights", category: "time" },
  日落: { en: "sunset dusk evening golden hour", category: "time" },
  日出: { en: "sunrise dawn morning golden", category: "time" },
  夕阳: { en: "sunset evening dusk golden", category: "time" },
  // === ACTIVITIES ===
  运动: { en: "sports exercise athletic game", category: "activity" },
  跑步: { en: "running jogging exercise outdoor", category: "activity" },
  游泳: { en: "swimming pool water sport", category: "activity" },
  骑车: { en: "cycling bicycle riding sport", category: "activity" },
  骑行: { en: "cycling bicycle riding road", category: "activity" },
  滑雪: { en: "skiing snow winter sport mountain", category: "activity" },
  钓鱼: { en: "fishing angling water outdoor", category: "activity" },
  爬山: { en: "hiking climbing mountain trail outdoor", category: "activity" },
  徒步: { en: "hiking walking trail outdoor nature", category: "activity" },
  露营: { en: "camping tent outdoor nature campfire", category: "activity" },
  野餐: { en: "picnic outdoor food blanket grass", category: "activity" },
  烧烤: { en: "barbecue grill food cooking outdoor", category: "activity" },
  做饭: { en: "cooking kitchen food preparation", category: "activity" },
  烹饪: { en: "cooking kitchen food preparation", category: "activity" },
  工作: { en: "working office desk computer", category: "activity" },
  学习: { en: "studying reading books desk", category: "activity" },
  阅读: { en: "reading book person indoor study", category: "activity" },
  旅行: { en: "travel journey trip vacation", category: "activity" },
  购物: { en: "shopping bags store mall", category: "activity" },
  散步: { en: "walking strolling path outdoor", category: "activity" },
  舞蹈: { en: "dancing performance movement", category: "activity" },
  唱歌: { en: "singing karaoke performance microphone", category: "activity" },
  音乐: { en: "music concert performance instrument", category: "activity" },
  绘画: { en: "painting drawing art creative", category: "activity" },
  瑜伽: { en: "yoga meditation stretching exercise", category: "activity" },
  聚会: {
    en: "party gathering celebration group people",
    category: "activity",
  },
  生日: { en: "birthday celebration party cake", category: "activity" },
  节日: { en: "festival celebration holiday decoration", category: "activity" },
  // === STYLE ===
  黑白: { en: "black and white monochrome grayscale", category: "style" },
  鲜艳: { en: "vivid colorful saturated vibrant", category: "style" },
  柔和: { en: "soft gentle pastel muted", category: "style" },
  模糊: { en: "blurry bokeh out of focus soft", category: "style" },
  清晰: { en: "sharp clear detailed crisp", category: "style" },
  微距: { en: "macro close-up detail tiny", category: "style" },
  特写: { en: "close-up macro detail zoom", category: "style" },
  逆光: { en: "backlight silhouette rim light", category: "style" },
  剪影: { en: "silhouette shadow dark outline shape", category: "style" },
  倒影: { en: "reflection mirror water surface symmetry", category: "style" },
  全景: { en: "panorama wide angle landscape view", category: "style" },
  广角: { en: "wide angle panorama expansive view", category: "style" },
  航拍: { en: "aerial drone top-down bird eye view", category: "style" },
  俯拍: { en: "aerial overhead top-down view", category: "style" },
  仰拍: { en: "low angle looking up perspective", category: "style" },
  对称: { en: "symmetry symmetric balanced centered", category: "style" },
  极简: { en: "minimalist simple clean empty space", category: "style" },
  复古: { en: "vintage retro film grain old", category: "style" },
  长曝光: { en: "long exposure light trails smooth water", category: "style" },
  多重曝光: { en: "double exposure overlay creative", category: "style" },
  平铺: { en: "flat lay top view arrangement", category: "style" },
  街拍: { en: "street photography candid urban life", category: "style" },
  抽象: { en: "abstract pattern texture artistic", category: "style" },
  涂鸦: { en: "graffiti street art urban wall colorful", category: "style" },
  壁画: { en: "mural wall painting art colorful", category: "style" },
  快乐: { en: "happy joyful smiling cheerful", category: "style" },
  悲伤: { en: "sad melancholy sorrowful", category: "style" },
  安静: { en: "quiet peaceful calm serene", category: "style" },
  热闹: { en: "lively bustling crowded energetic", category: "style" },
  浪漫: { en: "romantic love couple beautiful", category: "style" },
  孤独: { en: "lonely solitary alone single person", category: "style" },
  神秘: { en: "mysterious dark moody atmospheric", category: "style" },
  // === COLORS ===
  红色: { en: "red color warm", category: "color" },
  蓝色: { en: "blue color cool", category: "color" },
  绿色: { en: "green color nature", category: "color" },
  黄色: { en: "yellow color warm bright", category: "color" },
  白色: { en: "white color bright clean", category: "color" },
  黑色: { en: "black color dark", category: "color" },
  紫色: { en: "purple violet color", category: "color" },
  橙色: { en: "orange color warm", category: "color" },
  粉色: { en: "pink color soft", category: "color" },
  棕色: { en: "brown color earth", category: "color" },
  金色: { en: "gold golden color warm shiny", category: "color" },
  银色: { en: "silver metallic color grey shiny", category: "color" },
  // === WEATHER ===
  雨天: { en: "rain rainy wet weather", category: "weather" },
  雨中: { en: "rain rainy wet weather", category: "weather" },
  雨: { en: "rain rainy wet", category: "weather" },
  雪: { en: "snow winter cold white", category: "weather" },
  雪景: { en: "snow winter landscape white cold", category: "weather" },
  雪中: { en: "snow snowy winter cold", category: "weather" },
  雾: { en: "fog mist haze atmosphere", category: "weather" },
  阴天: { en: "cloudy overcast grey sky", category: "weather" },
  晴天: { en: "sunny clear blue sky bright", category: "weather" },
  大风: { en: "windy wind blowing weather", category: "weather" },
  暴风雨: { en: "storm thunderstorm rain lightning", category: "weather" },
  彩虹: { en: "rainbow colorful sky rain sun", category: "weather" },
  闪电: { en: "lightning storm sky thunder", category: "weather" },
  星空: { en: "starry night sky stars", category: "weather" },
  月亮: { en: "moon night sky", category: "weather" },
  太阳: { en: "sun bright sky daytime", category: "weather" },
  蓝天: { en: "blue sky clear sunny", category: "weather" },
  白云: { en: "white clouds sky", category: "weather" },
  极光: { en: "aurora northern lights sky night", category: "weather" },
  烟花: { en: "fireworks celebration night sky colorful", category: "weather" },
  // === CLOTHING & APPEARANCE ===
  红裙: { en: "red dress skirt woman clothing", category: "object" },
  红裙子: { en: "red dress skirt woman clothing", category: "object" },
  白衬衫: { en: "white shirt clothing person", category: "object" },
  西装: { en: "suit formal business clothing man", category: "object" },
  旗袍: { en: "cheongsam traditional Chinese dress woman", category: "object" },
  长发: { en: "long hair woman flowing", category: "object" },
  短发: { en: "short hair person", category: "object" },
  // === NATURE DETAILS ===
  风景: { en: "landscape scenery nature", category: "scene" },
  自然风景: { en: "landscape scenery nature", category: "scene" },
  叶子: { en: "leaf plant green nature", category: "object" },
  红叶: { en: "red leaf autumn fall maple", category: "object" },
  枫叶: { en: "maple leaf autumn fall red nature", category: "object" },
  银杏: { en: "ginkgo leaf yellow autumn tree nature", category: "object" },
  银杏叶: { en: "ginkgo leaf yellow autumn nature", category: "object" },
  柳树: { en: "willow tree branches green nature", category: "object" },
  桃花: { en: "peach blossom pink flower spring", category: "object" },
  梅花: { en: "plum blossom flower winter pink white", category: "object" },
  兰花: { en: "orchid flower elegant purple white", category: "object" },
  竹林: { en: "bamboo forest green tall nature", category: "scene" },
  仙人掌: { en: "cactus plant desert green spiky", category: "object" },
  薰衣草: { en: "lavender flower purple field nature", category: "object" },
  芦苇: { en: "reed grass water marsh nature", category: "object" },
  爬山虎: { en: "ivy vine wall green climbing plant", category: "object" },
  樱花: { en: "cherry blossom pink flower spring", category: "object" },
  荷花: { en: "lotus flower water lily pond", category: "object" },
  莲花: { en: "lotus flower water lily pond", category: "object" },
  玫瑰: { en: "rose flower red romantic", category: "object" },
  向日葵: { en: "sunflower yellow flower bright field", category: "object" },
  郁金香: { en: "tulip flower colorful spring", category: "object" },
  菊花: { en: "chrysanthemum flower autumn", category: "object" },
  蒲公英: { en: "dandelion flower fluffy seed white", category: "object" },
  蘑菇: { en: "mushroom fungus forest ground", category: "object" },
  竹子: { en: "bamboo plant green tall", category: "object" },
  松树: { en: "pine tree evergreen conifer", category: "object" },
  花海: { en: "flower field garden colorful vast", category: "scene" },
  绿树: { en: "green tree forest lush", category: "scene" },
  贝壳: { en: "seashell shell beach ocean sand", category: "object" },
  珊瑚: { en: "coral reef underwater ocean colorful", category: "object" },
  // === ANIMALS (extended) ===
  企鹅: { en: "penguin bird antarctic black white", category: "subject" },
  海豚: { en: "dolphin ocean sea swimming intelligent", category: "subject" },
  鲸鱼: { en: "whale ocean sea huge marine", category: "subject" },
  鲨鱼: { en: "shark fish ocean predator marine", category: "subject" },
  乌龟: { en: "turtle tortoise shell reptile slow", category: "subject" },
  螃蟹: { en: "crab crustacean ocean beach claws", category: "subject" },
  鹦鹉: { en: "parrot bird colorful tropical pet", category: "subject" },
  孔雀: { en: "peacock bird colorful feathers beautiful", category: "subject" },
  天鹅: { en: "swan bird white elegant lake water", category: "subject" },
  长颈鹿: { en: "giraffe animal tall neck spotted wild", category: "subject" },
  斑马: { en: "zebra animal stripes black white wild", category: "subject" },
  北极熊: { en: "polar bear white arctic snow animal", category: "subject" },
  海龟: { en: "sea turtle ocean marine reptile", category: "subject" },
  水母: { en: "jellyfish ocean sea translucent marine", category: "subject" },
  章鱼: { en: "octopus ocean sea tentacles marine", category: "subject" },
  蜗牛: { en: "snail shell slow garden insect", category: "subject" },
  瓢虫: { en: "ladybug insect red spotted small", category: "subject" },
  萤火虫: { en: "firefly insect glowing night nature", category: "subject" },
  // === FOOD & DRINKS ===
  西瓜: { en: "watermelon fruit green red summer", category: "object" },
  苹果: { en: "apple fruit red green fresh", category: "object" },
  香蕉: { en: "banana fruit yellow tropical", category: "object" },
  橙子: { en: "orange fruit citrus fresh", category: "object" },
  葡萄: { en: "grape fruit purple green bunch", category: "object" },
  樱桃: { en: "cherry fruit red sweet small", category: "object" },
  芒果: { en: "mango fruit yellow tropical sweet", category: "object" },
  柠檬: { en: "lemon fruit yellow citrus sour", category: "object" },
  桃子: { en: "peach fruit pink sweet juicy", category: "object" },
  披萨: { en: "pizza food cheese Italian round", category: "object" },
  汉堡: { en: "hamburger burger food sandwich fast food", category: "object" },
  寿司: { en: "sushi Japanese food rice fish", category: "object" },
  面条: { en: "noodles pasta food dish", category: "object" },
  冰淇淋: { en: "ice cream dessert sweet cold", category: "object" },
  巧克力: { en: "chocolate dessert sweet brown candy", category: "object" },
  糖果: { en: "candy sweets colorful sugar", category: "object" },
  // === OBJECTS (extended) ===
  花瓶: { en: "vase flower container ceramic glass", category: "object" },
  时钟: { en: "clock time wall antique", category: "object" },
  手表: { en: "watch wrist time accessory", category: "object" },
  项链: { en: "necklace jewelry accessory gold silver", category: "object" },
  戒指: { en: "ring jewelry finger gold diamond", category: "object" },
  围巾: { en: "scarf neck clothing accessory winter", category: "object" },
  手套: { en: "gloves hand clothing winter", category: "object" },
  钥匙: { en: "key metal lock door", category: "object" },
  地图: { en: "map paper navigation geography", category: "object" },
  望远镜: { en: "telescope binoculars observation", category: "object" },
  放大镜: { en: "magnifying glass lens inspection", category: "object" },
  行李箱: { en: "suitcase luggage travel bag", category: "object" },
  背包: { en: "backpack bag travel hiking school", category: "object" },
  // === SCENES (extended) ===
  港口: { en: "harbor port dock ships water", category: "scene" },
  岛屿: { en: "island ocean sea tropical beach", category: "scene" },
  温泉: { en: "hot spring water steam nature relaxation", category: "scene" },
  绿洲: { en: "oasis desert water palm trees", category: "scene" },
  雨林: { en: "rainforest jungle tropical trees nature", category: "scene" },
  雪山: { en: "snow mountain peak winter cold white", category: "scene" },
  梯田: { en: "terrace rice field agriculture hillside", category: "scene" },
  古镇: { en: "ancient town historic traditional architecture", category: "scene" },
  摩天轮: { en: "ferris wheel amusement park ride", category: "object" },
  游乐场: { en: "amusement park playground rides fun", category: "scene" },
  书店: { en: "bookstore book shop reading indoor", category: "scene" },
  花店: { en: "flower shop store colorful indoor", category: "scene" },
  // === WEATHER (extended) ===
  晚霞: { en: "sunset glow evening red sky clouds", category: "weather" },
  朝霞: { en: "sunrise glow morning red sky clouds", category: "weather" },
  冰雹: { en: "hail ice storm weather", category: "weather" },
  沙尘暴: { en: "sandstorm dust storm desert weather", category: "weather" },
  // === ACTIVITIES (extended) ===
  拍照: { en: "photography taking photo camera picture", category: "activity" },
  摄影: { en: "photography camera shooting picture", category: "activity" },
  锻炼: { en: "exercise workout fitness gym training", category: "activity" },
  健身: { en: "fitness gym workout exercise training", category: "activity" },
  冥想: { en: "meditation yoga peace calm sitting", category: "activity" },
  冲浪: { en: "surfing wave ocean water sport beach", category: "activity" },
  滑冰: { en: "ice skating winter sport rink", category: "activity" },
  潜水: { en: "diving underwater ocean swimming", category: "activity" },
  // === STYLE (extended) ===
  日系: { en: "Japanese style clean minimal bright", category: "style" },
  森系: { en: "forest style natural green earthy", category: "style" },
  电影感: { en: "cinematic film movie dramatic moody", category: "style" },
  小清新: { en: "fresh clean bright airy minimalist aesthetic", category: "style" },
  国风: { en: "Chinese traditional style guofeng oriental ancient costume hanfu ink painting elegant", category: "style" },
  水墨: { en: "ink wash painting sumi-e black white monochrome brush stroke traditional Chinese art", category: "style" },
  水墨画: { en: "ink wash painting sumi-e black white monochrome brush stroke traditional Chinese art", category: "style" },
  工笔画: { en: "gongbi fine brushwork detailed traditional Chinese painting meticulous", category: "style" },
  写意: { en: "xieyi freehand brushwork expressive traditional Chinese painting spontaneous", category: "style" },
  青花瓷: { en: "blue and white porcelain ceramic Chinese traditional pattern pottery", category: "object" },
  古风: { en: "ancient Chinese style traditional classical antique historical elegant", category: "style" },
  汉服: { en: "hanfu traditional Chinese clothing costume robe silk ancient dress", category: "object" },
  唐装: { en: "Tang suit traditional Chinese clothing costume silk elegant", category: "object" },
  中国风: { en: "Chinese style traditional oriental chinoiserie elegant red gold", category: "style" },
  禅意: { en: "zen meditation tranquil peaceful minimal Japanese Chinese aesthetic simplicity", category: "style" },
  留白: { en: "negative space minimalist empty blank simplicity composition aesthetic", category: "style" },
  工笔: { en: "fine brushwork detailed meticulous traditional Chinese painting gongbi", category: "style" },
  白描: { en: "line drawing outline sketch black white simple traditional Chinese", category: "style" },
  淡彩: { en: "light color wash watercolor subtle soft pastel traditional painting", category: "style" },
  重彩: { en: "heavy color rich saturated bold vibrant traditional Chinese painting", category: "style" },
  仕女图: { en: "traditional Chinese painting of beautiful women ancient court ladies", category: "object" },
  花鸟画: { en: "flower and bird painting traditional Chinese nature art", category: "object" },
  山水画: { en: "landscape painting shanshui traditional Chinese mountain water art", category: "object" },
  书法: { en: "calligraphy brush writing ink Chinese characters art handwrite", category: "object" },
  篆刻: { en: "seal carving stamp chop Chinese traditional art calligraphy", category: "object" },
  屏风: { en: "folding screen room divider traditional Chinese furniture decorative oriental", category: "object" },
  折扇: { en: "folding fan Chinese traditional accessory paper bamboo elegant", category: "object" },
  团扇: { en: "round fan silk traditional Chinese accessory elegant moon shaped", category: "object" },
  灯笼: { en: "lantern red traditional Chinese decoration festive light", category: "object" },
  对联: { en: "couplet red paper calligraphy Chinese new year decoration traditional", category: "object" },
  窗花: { en: "papercut window decoration red traditional Chinese folk art", category: "object" },
  剪纸: { en: "papercut traditional Chinese folk art red paper scissors handcraft", category: "object" },
  刺绣: { en: "embroidery silk thread needle traditional Chinese textile art handcraft", category: "object" },
  染布: { en: "dyed fabric textile indigo tie-dye traditional Chinese cloth craft", category: "object" },
  瓦当: { en: "roof tile end eaves traditional Chinese architecture decorative pattern", category: "object" },
  斗拱: { en: "dougong bracket set traditional Chinese architecture wooden structure temple", category: "object" },
  园林: { en: "Chinese garden classical landscape pavilion pond rockery traditional architecture", category: "scene" },
  庭院: { en: "courtyard traditional Chinese house garden peaceful classical architecture", category: "scene" },
  四合院: { en: "siheyuan traditional Chinese courtyard house quadrangle architecture Beijing", category: "scene" },
  胡同: { en: "hutong narrow alley traditional Beijing neighborhood old street China", category: "scene" },
  // === ARCHITECTURE DETAILS ===
  屋顶: { en: "roof top building architecture", category: "scene" },
  阳台: { en: "balcony terrace outdoor building", category: "scene" },
  楼梯: { en: "staircase stairs steps architecture", category: "scene" },
  走廊: { en: "corridor hallway passage indoor", category: "scene" },
  路灯: { en: "streetlight lamp post night urban", category: "object" },
  // === MISC ===
  文字: { en: "text document writing", category: "object" },
  截图: { en: "screenshot screen ui", category: "object" },
  屏幕截图: { en: "screenshot screen ui", category: "object" },
  火焰: { en: "fire flame burn hot", category: "object" },
  篝火: { en: "bonfire campfire fire flame night", category: "object" },
};

// Character-level decomposition for unknown compound words.
// When a multi-character word isn't in the dictionary, we try splitting
// it into individual characters and translating each one.
export const CHAR_DECOMPOSE: Record<
  string,
  { en: string; category: DictCategory }
> = {
  红: { en: "red", category: "color" },
  蓝: { en: "blue", category: "color" },
  绿: { en: "green", category: "color" },
  黄: { en: "yellow", category: "color" },
  白: { en: "white", category: "color" },
  黑: { en: "black", category: "color" },
  紫: { en: "purple", category: "color" },
  粉: { en: "pink", category: "color" },
  金: { en: "gold golden", category: "color" },
  灰: { en: "grey gray", category: "color" },
  裙: { en: "dress skirt", category: "object" },
  衫: { en: "shirt top", category: "object" },
  裤: { en: "pants trousers", category: "object" },
  帽: { en: "hat cap", category: "object" },
  鞋: { en: "shoes", category: "object" },
  包: { en: "bag", category: "object" },
  伞: { en: "umbrella", category: "object" },
  女: { en: "female woman", category: "subject" },
  男: { en: "male man", category: "subject" },
  老: { en: "old elderly", category: "subject" },
  少: { en: "young", category: "subject" },
  小: { en: "small little young", category: "object" },
  大: { en: "large big", category: "object" },
  长: { en: "long tall", category: "object" },
  短: { en: "short", category: "object" },
  高: { en: "tall high", category: "scene" },
  低: { en: "low short", category: "scene" },
  新: { en: "new", category: "object" },
  旧: { en: "old vintage", category: "style" },
  亮: { en: "bright light", category: "style" },
  暗: { en: "dark dim", category: "style" },
  冷: { en: "cold cool", category: "weather" },
  热: { en: "hot warm", category: "weather" },
  湿: { en: "wet damp", category: "weather" },
  干: { en: "dry", category: "weather" },
  远: { en: "far distant", category: "scene" },
  近: { en: "near close", category: "scene" },
  花: { en: "flower", category: "object" },
  草: { en: "grass green", category: "scene" },
  树: { en: "tree", category: "scene" },
  山: { en: "mountain", category: "scene" },
  水: { en: "water", category: "scene" },
  石: { en: "stone rock", category: "object" },
  云: { en: "cloud", category: "weather" },
  风: { en: "wind", category: "weather" },
  雨: { en: "rain", category: "weather" },
  雪: { en: "snow", category: "weather" },
  日: { en: "sun day", category: "time" },
  月: { en: "moon month", category: "time" },
  星: { en: "star", category: "weather" },
  夜: { en: "night", category: "time" },
  晨: { en: "morning dawn", category: "time" },
  午: { en: "noon midday", category: "time" },
  秋: { en: "autumn fall", category: "time" },
  春: { en: "spring", category: "time" },
  夏: { en: "summer", category: "time" },
  冬: { en: "winter", category: "time" },
  海: { en: "sea ocean", category: "scene" },
  河: { en: "river", category: "scene" },
  湖: { en: "lake", category: "scene" },
  路: { en: "road path", category: "scene" },
  桥: { en: "bridge", category: "scene" },
  门: { en: "door gate", category: "object" },
  窗: { en: "window", category: "object" },
  灯: { en: "light lamp", category: "object" },
  火: { en: "fire flame", category: "object" },
  车: { en: "car vehicle", category: "object" },
  船: { en: "boat ship", category: "object" },
  猫: { en: "cat", category: "subject" },
  狗: { en: "dog", category: "subject" },
  鸟: { en: "bird", category: "subject" },
  鱼: { en: "fish", category: "subject" },
  // === 扩展单字：植物 ===
  银: { en: "silver", category: "color" },
  杏: { en: "apricot almond", category: "object" },
  叶: { en: "leaf", category: "object" },
  枫: { en: "maple", category: "object" },
  松: { en: "pine", category: "object" },
  竹: { en: "bamboo", category: "object" },
  梅: { en: "plum blossom", category: "object" },
  兰: { en: "orchid", category: "object" },
  菊: { en: "chrysanthemum", category: "object" },
  桃: { en: "peach", category: "object" },
  柳: { en: "willow", category: "object" },
  杨: { en: "poplar", category: "object" },
  柏: { en: "cypress", category: "object" },
  杉: { en: "fir cedar", category: "object" },
  榕: { en: "banyan", category: "object" },
  莲: { en: "lotus", category: "object" },
  荷: { en: "lotus", category: "object" },
  桂: { en: "osmanthus laurel", category: "object" },
  荔: { en: "lychee", category: "object" },
  芒: { en: "mango", category: "object" },
  莓: { en: "berry strawberry", category: "object" },
  葡: { en: "grape", category: "object" },
  萄: { en: "grape", category: "object" },
  蕉: { en: "banana", category: "object" },
  藤: { en: "vine climbing plant", category: "object" },
  苗: { en: "seedling sprout", category: "object" },
  芽: { en: "bud sprout", category: "object" },
  蕊: { en: "stamen pistil flower center", category: "object" },
  棘: { en: "thorn spine", category: "object" },
  // === 扩展单字：动物 ===
  虫: { en: "insect bug", category: "subject" },
  蛙: { en: "frog", category: "subject" },
  蟹: { en: "crab", category: "subject" },
  虾: { en: "shrimp", category: "subject" },
  贝: { en: "shell shellfish", category: "object" },
  龟: { en: "turtle tortoise", category: "subject" },
  鲸: { en: "whale", category: "subject" },
  鲨: { en: "shark", category: "subject" },
  豚: { en: "dolphin", category: "subject" },
  鹅: { en: "goose", category: "subject" },
  鸭: { en: "duck", category: "subject" },
  鸡: { en: "chicken hen rooster", category: "subject" },
  鸽: { en: "pigeon dove", category: "subject" },
  鹰: { en: "eagle hawk", category: "subject" },
  狼: { en: "wolf", category: "subject" },
  熊: { en: "bear", category: "subject" },
  豹: { en: "leopard panther", category: "subject" },
  鼠: { en: "mouse rat rodent", category: "subject" },
  蜂: { en: "bee wasp", category: "subject" },
  蝶: { en: "butterfly", category: "subject" },
  蝇: { en: "fly insect", category: "subject" },
  蚊: { en: "mosquito", category: "subject" },
  蛛: { en: "spider", category: "subject" },
  蚕: { en: "silkworm caterpillar", category: "subject" },
  蝉: { en: "cicada", category: "subject" },
  蜗: { en: "snail", category: "subject" },
  // === 扩展单字：自然 ===
  冰: { en: "ice frozen", category: "weather" },
  霜: { en: "frost", category: "weather" },
  露: { en: "dew", category: "weather" },
  霞: { en: "rosy clouds sunset glow", category: "weather" },
  虹: { en: "rainbow", category: "weather" },
  雷: { en: "thunder lightning", category: "weather" },
  电: { en: "lightning electric", category: "weather" },
  沙: { en: "sand", category: "scene" },
  尘: { en: "dust", category: "scene" },
  泥: { en: "mud clay", category: "scene" },
  岩: { en: "rock cliff", category: "scene" },
  峰: { en: "peak summit", category: "scene" },
  岭: { en: "ridge mountain", category: "scene" },
  谷: { en: "valley", category: "scene" },
  洞: { en: "cave hole", category: "scene" },
  穴: { en: "cave den", category: "scene" },
  泉: { en: "spring fountain", category: "scene" },
  池: { en: "pond pool", category: "scene" },
  塘: { en: "pond", category: "scene" },
  湾: { en: "bay cove", category: "scene" },
  岛: { en: "island", category: "scene" },
  滩: { en: "beach shore", category: "scene" },
  漠: { en: "desert", category: "scene" },
  崖: { en: "cliff", category: "scene" },
  瀑: { en: "waterfall", category: "scene" },
  溪: { en: "stream creek", category: "scene" },
  // === 扩展单字：色彩/视觉 ===
  艳: { en: "vivid colorful bright", category: "style" },
  淡: { en: "light pale soft", category: "style" },
  深: { en: "deep dark intense", category: "style" },
  浅: { en: "shallow light pale", category: "style" },
  素: { en: "plain simple", category: "style" },
  鲜: { en: "fresh vivid bright", category: "style" },
  彩: { en: "colorful rainbow", category: "style" },
  透: { en: "transparent clear", category: "style" },
  // === 扩展单字：身体/人物 ===
  手: { en: "hand", category: "subject" },
  脚: { en: "foot feet", category: "subject" },
  眼: { en: "eye", category: "subject" },
  耳: { en: "ear", category: "subject" },
  鼻: { en: "nose", category: "subject" },
  嘴: { en: "mouth", category: "subject" },
  唇: { en: "lip", category: "subject" },
  齿: { en: "tooth teeth", category: "subject" },
  舌: { en: "tongue", category: "subject" },
  眉: { en: "eyebrow", category: "subject" },
  指: { en: "finger", category: "subject" },
  掌: { en: "palm hand", category: "subject" },
  臂: { en: "arm", category: "subject" },
  腿: { en: "leg", category: "subject" },
  身: { en: "body figure", category: "subject" },
  影: { en: "shadow silhouette", category: "style" },
  背: { en: "back behind", category: "subject" },
  肩: { en: "shoulder", category: "subject" },
  颈: { en: "neck", category: "subject" },
  腰: { en: "waist", category: "subject" },
  // === 扩展单字：建筑/场所 ===
  房: { en: "house room", category: "scene" },
  屋: { en: "house cottage", category: "scene" },
  楼: { en: "building tower", category: "scene" },
  堂: { en: "hall", category: "scene" },
  馆: { en: "hall gallery museum", category: "scene" },
  店: { en: "shop store", category: "scene" },
  铺: { en: "shop store", category: "scene" },
  厂: { en: "factory industrial", category: "scene" },
  园: { en: "garden park", category: "scene" },
  院: { en: "courtyard yard", category: "scene" },
  庭: { en: "courtyard garden", category: "scene" },
  巷: { en: "alley lane", category: "scene" },
  街: { en: "street", category: "scene" },
  城: { en: "city town", category: "scene" },
  镇: { en: "town", category: "scene" },
  村: { en: "village rural", category: "scene" },
  庄: { en: "village farm", category: "scene" },
  庙: { en: "temple shrine", category: "scene" },
  塔: { en: "tower pagoda", category: "scene" },
  碑: { en: "monument stone tablet", category: "object" },
  柱: { en: "pillar column", category: "object" },
  拱: { en: "arch", category: "object" },
  // === 扩展单字：物品 ===
  纸: { en: "paper", category: "object" },
  笔: { en: "pen pencil writing", category: "object" },
  杯: { en: "cup glass", category: "object" },
  碗: { en: "bowl", category: "object" },
  盘: { en: "plate dish", category: "object" },
  瓶: { en: "bottle", category: "object" },
  罐: { en: "jar can", category: "object" },
  箱: { en: "box chest", category: "object" },
  柜: { en: "cabinet", category: "object" },
  架: { en: "shelf rack frame", category: "object" },
  梯: { en: "ladder stairs", category: "object" },
  栏: { en: "fence railing", category: "object" },
  杆: { en: "pole rod", category: "object" },
  绳: { en: "rope cord", category: "object" },
  网: { en: "net web mesh", category: "object" },
  布: { en: "cloth fabric", category: "object" },
  巾: { en: "towel scarf", category: "object" },
  毯: { en: "blanket carpet", category: "object" },
  枕: { en: "pillow", category: "object" },
  被: { en: "blanket quilt", category: "object" },
  帘: { en: "curtain", category: "object" },
  钟: { en: "clock bell", category: "object" },
  表: { en: "watch clock", category: "object" },
  链: { en: "chain necklace", category: "object" },
  环: { en: "ring circle", category: "object" },
  珠: { en: "pearl bead", category: "object" },
  锁: { en: "lock", category: "object" },
  钥: { en: "key", category: "object" },
  剪: { en: "scissors", category: "object" },
  针: { en: "needle pin", category: "object" },
  线: { en: "thread line wire", category: "object" },
  袋: { en: "bag sack", category: "object" },
  篮: { en: "basket", category: "object" },
  笼: { en: "cage basket", category: "object" },
  扇: { en: "fan", category: "object" },
  琴: { en: "musical instrument piano zither", category: "object" },
  笛: { en: "flute", category: "object" },
  鼓: { en: "drum", category: "object" },
  棋: { en: "chess board game", category: "object" },
  书: { en: "book", category: "object" },
  画: { en: "painting picture drawing", category: "object" },
  照: { en: "photo picture", category: "object" },
  镜: { en: "mirror lens", category: "object" },
  像: { en: "image portrait statue", category: "object" },
  玩: { en: "toy play", category: "object" },
  偶: { en: "doll puppet", category: "object" },
  // === 扩展单字：动作 ===
  跑: { en: "running", category: "activity" },
  跳: { en: "jumping leaping", category: "activity" },
  走: { en: "walking", category: "activity" },
  坐: { en: "sitting seated", category: "activity" },
  站: { en: "standing", category: "activity" },
  躺: { en: "lying down", category: "activity" },
  飞: { en: "flying", category: "activity" },
  游: { en: "swimming", category: "activity" },
  爬: { en: "climbing crawling", category: "activity" },
  骑: { en: "riding cycling", category: "activity" },
  唱: { en: "singing", category: "activity" },
  读: { en: "reading", category: "activity" },
  吃: { en: "eating dining", category: "activity" },
  喝: { en: "drinking", category: "activity" },
  睡: { en: "sleeping", category: "activity" },
  笑: { en: "smiling laughing", category: "activity" },
  哭: { en: "crying", category: "activity" },
  抱: { en: "hugging holding", category: "activity" },
  舞: { en: "dancing", category: "activity" },
  钓: { en: "fishing", category: "activity" },
  写: { en: "writing", category: "activity" },
  拍: { en: "photographing taking picture", category: "activity" },
  // === 扩展单字：时间/方位 ===
  早: { en: "morning early", category: "time" },
  晚: { en: "evening late night", category: "time" },
  晓: { en: "dawn morning", category: "time" },
  暮: { en: "dusk twilight", category: "time" },
  昏: { en: "dusk dim", category: "time" },
  旦: { en: "dawn daybreak", category: "time" },
  夕: { en: "sunset evening", category: "time" },
  朝: { en: "morning", category: "time" },
  // === 扩展单字：品质/形状 ===
  美: { en: "beautiful pretty", category: "style" },
  丽: { en: "beautiful gorgeous", category: "style" },
  圆: { en: "round circular", category: "style" },
  方: { en: "square rectangular", category: "style" },
  尖: { en: "pointed sharp", category: "style" },
  平: { en: "flat level", category: "style" },
  弯: { en: "curved bent", category: "style" },
  直: { en: "straight", category: "style" },
  厚: { en: "thick", category: "style" },
  薄: { en: "thin", category: "style" },
  轻: { en: "light lightweight", category: "style" },
  重: { en: "heavy", category: "style" },
  软: { en: "soft", category: "style" },
  硬: { en: "hard rigid", category: "style" },
  粗: { en: "rough coarse", category: "style" },
  细: { en: "thin fine delicate", category: "style" },
  滑: { en: "smooth slippery", category: "style" },
  毛: { en: "furry hairy", category: "style" },
  光: { en: "shiny glossy light", category: "style" },
  油: { en: "oily greasy", category: "style" },
  // === 扩展单字：天气/环境 ===
  暖: { en: "warm", category: "weather" },
  凉: { en: "cool", category: "weather" },
  潮: { en: "humid moist damp", category: "weather" },
  燥: { en: "dry arid", category: "weather" },
  晴: { en: "sunny clear", category: "weather" },
  阴: { en: "cloudy overcast", category: "weather" },
  雾: { en: "fog mist", category: "weather" },
  烟: { en: "smoke haze", category: "weather" },
  汽: { en: "steam vapor", category: "weather" },
  浪: { en: "wave surf", category: "scene" },
  波: { en: "wave ripple", category: "scene" },
  流: { en: "flowing stream", category: "scene" },
  滴: { en: "drop droplet", category: "scene" },
};
