// Chinese -> English search keyword mapping.
// CLIP ViT-B/32 was trained on English image-text pairs, so Chinese queries
// produce poor alignment. We translate known Chinese terms to English before
// embedding to improve search accuracy.

export const ZH_TO_EN_SEARCH: Record<string, string> = {
  猫: "cat kitten",
  猫咪: "cat kitten",
  狗: "dog puppy",
  狗狗: "dog puppy",
  人: "person people human",
  人物: "person people human portrait",
  花: "flower blossom",
  花卉: "flower blossom",
  车: "car vehicle automobile",
  汽车: "car vehicle automobile",
  建筑: "building architecture",
  海: "ocean sea beach water",
  海滩: "beach sand ocean",
  山: "mountain hill",
  山脉: "mountain hill",
  树: "tree plant forest",
  树木: "tree plant forest",
  天空: "sky clouds",
  云: "clouds sky",
  日落: "sunset evening dusk",
  日出: "sunrise dawn morning",
  夜景: "night scene dark",
  夜晚: "night dark",
  食物: "food meal dish",
  美食: "food meal dish",
  室内: "indoor room inside",
  户外: "outdoor outside",
  城市: "city urban street",
  黑白: "black and white monochrome",
  雪: "snow winter cold",
  鸟: "bird",
  鸟类: "bird",
  鱼: "fish underwater",
  昆虫: "insect bug",
  桥: "bridge",
  路: "road street path",
  街道: "street road urban",
  门: "door entrance",
  窗: "window",
  桌子: "table desk furniture",
  椅子: "chair furniture",
  书: "book reading",
  书籍: "book reading",
  手机: "phone smartphone cellphone",
  电脑: "computer laptop pc",
  红色: "red color",
  蓝色: "blue color",
  绿色: "green color",
  黄色: "yellow color",
  白色: "white color bright",
  黑色: "black color dark",
  秋天: "autumn fall season",
  春天: "spring season",
  夏天: "summer season",
  冬天: "winter snow season",
  风景: "landscape scenery nature",
  自然风景: "landscape scenery nature",
  人像: "portrait person face",
  微距: "macro close-up detail",
  逆光: "backlight silhouette",
  动物: "animal wildlife",
  文字: "text document writing",
  截图: "screenshot screen ui",
  屏幕截图: "screenshot screen ui",
  水: "water lake river ocean",
  水面: "water surface reflection",
  草地: "grass field meadow green",
  沙滩: "beach sand shore",
  夕阳: "sunset evening dusk",
  森林: "forest woods trees nature",
  花园: "garden flowers park",
  湖: "lake water reflection",
  湖泊: "lake water reflection",
  河: "river stream water",
  河流: "river stream water",
  雾: "fog mist atmosphere",
  飞机: "airplane aircraft sky",
  船: "boat ship water",
  自行车: "bicycle bike",
  摩托车: "motorcycle bike",
  花海: "flower field garden colorful",
  红叶: "red leaf autumn fall",
  雪景: "snow winter landscape white",
  蓝天: "blue sky clear",
  白云: "white clouds sky",
  绿树: "green tree forest",
  大海: "ocean sea blue water",
  高山: "tall mountain peak",
  小溪: "stream creek water",
  瀑布: "waterfall water cascade",
  彩虹: "rainbow sky colorful",
  闪电: "lightning storm sky",
  星空: "starry night sky stars",
  月亮: "moon night sky",
  太阳: "sun bright sky daytime",
  // Extended vocabulary
  草莓: "strawberry",
  水果: "fruit",
  蔬菜: "vegetable",
  蛋糕: "cake dessert",
  面包: "bread",
  咖啡: "coffee",
  饮料: "drink beverage",
  孩子: "child kid baby young person",
  婴儿: "baby infant newborn person",
  老人: "elderly senior old person",
  婚礼: "wedding ceremony bride groom celebration",
  生日: "birthday celebration party cake",
  聚会: "party gathering celebration group people",
  运动: "sports exercise activity game",
  舞蹈: "dance dancing performance person",
  音乐: "music concert performance instrument",
  眼镜: "glasses eyewear spectacles person face",
  帽子: "hat cap headwear person",
  鞋子: "shoes footwear sneakers",
  衣服: "clothing outfit dress garment",
  包: "bag handbag backpack purse",
  灯: "lamp light lighting illumination",
  蜡烛: "candle flame light fire",
  玩具: "toy doll plaything child",
  乐器: "musical instrument guitar piano music",
  吉他: "guitar musical instrument string music",
  钢琴: "piano keyboard musical instrument",
  相机: "camera photography lens equipment",
  叶子: "leaf plant green nature",
  火焰: "fire flame burn hot",
  沙漠: "desert sand dry arid nature",
  极光: "aurora northern lights sky night nature",
  雨天: "rain wet weather umbrella water",
  枫叶: "maple leaf autumn fall red nature",
  樱花: "cherry blossom pink flower spring nature",
  教堂: "church cathedral building architecture",
  寺庙: "temple building architecture religious",
  城堡: "castle building architecture historic",
  塔: "tower tall building structure architecture",
  公园: "park garden green nature outdoor",
  市场: "market shopping bazaar stall people",
  餐厅: "restaurant dining food table indoor",
  厨房: "kitchen cooking room indoor food",
  卧室: "bedroom bed sleeping room indoor",
  办公室: "office desk workspace computer indoor",
  兔子: "rabbit bunny animal pet",
  熊猫: "panda bear animal black white",
  老虎: "tiger animal wild cat predator",
  狮子: "lion animal wild cat predator",
  大象: "elephant animal large wild",
  猴子: "monkey animal primate wild",
  蛇: "snake reptile animal wild",
  蝴蝶: "butterfly insect colorful wings nature",
  马: "horse animal running field",
  牛: "cow cattle animal farm",
  羊: "sheep lamb animal wool farm",
  紫色: "purple violet color",
  橙色: "orange color warm",
  粉色: "pink color soft",
  棕色: "brown color earth",
  鲜艳: "vivid bright colorful saturated",
  柔和: "soft gentle pastel muted color",
  模糊: "blurry bokeh out of focus soft",
  清晰: "sharp clear detailed crisp",
  倒影: "reflection mirror water surface",
  剪影: "silhouette shadow dark outline shape",
  特写: "close-up macro detail zoom",
  广角: "wide angle panorama expansive view",
  节日: "festival celebration holiday decoration",
  烟花: "fireworks celebration night sky colorful",
  路灯: "streetlight lamp post night urban",
  钟楼: "clock tower bell building architecture",
  雕塑: "sculpture statue art monument",
  喷泉: "fountain water spray garden urban",
  涂鸦: "graffiti street art urban wall colorful",
  壁画: "mural wall painting art colorful",
  屋顶: "roof top building architecture",
  窗户: "window glass building architecture",
  阳台: "balcony terrace outdoor building",
  楼梯: "staircase stairs steps indoor architecture",
  走廊: "corridor hallway passage indoor architecture",
  拱门: "arch doorway entrance architecture",
  柱子: "pillar column architecture building",
  栅栏: "fence barrier wood metal outdoor",
  旗帜: "flag banner symbol wind outdoor",
  灯笼: "lantern light decoration red festive",
  气球: "balloon colorful celebration party decoration",
  礼物: "gift present box package celebration",
  彩带: "ribbon streamer decoration colorful celebration",
  // Botanicals & nature
  蒲公英: "dandelion flower fluffy seed white",
  贝壳: "seashell shell beach ocean sand",
  海螺: "seashell conch shell spiral ocean",
  松树: "pine tree evergreen conifer forest",
  竹子: "bamboo plant green tall forest",
  荷花: "lotus flower water lily pond blossom",
  莲花: "lotus flower water lily pond blossom",
  玫瑰: "rose flower red romantic blossom",
  向日葵: "sunflower yellow flower bright field",
  郁金香: "tulip flower colorful spring blossom",
  菊花: "chrysanthemum flower yellow autumn blossom",
  蘑菇: "mushroom fungus forest ground plant",
  珊瑚: "coral reef underwater ocean colorful",
  海星: "starfish sea ocean beach marine",
  // Animals extended
  鸽子: "pigeon dove bird white grey urban",
  猫头鹰: "owl bird nocturnal wise predator",
  松鼠: "squirrel animal rodent tree forest",
  鹿: "deer animal wildlife forest antler",
  狐狸: "fox animal wild orange clever predator",
  老鹰: "eagle hawk bird predator sky wildlife",
  蚂蚁: "ant insect small ground macro",
  蜜蜂: "bee insect honey flower yellow macro",
  蜻蜓: "dragonfly insect wings colorful macro nature",
  // People & activities
  自拍: "selfie person face camera phone portrait",
  跑步: "running jogging exercise sport person",
  游泳: "swimming pool water sport person",
  滑雪: "skiing snow winter sport mountain person",
  钓鱼: "fishing angling water outdoor person",
  骑车: "cycling bicycle riding sport outdoor person",
  露营: "camping tent outdoor nature campfire",
  烧烤: "barbecue grill food cooking outdoor fire",
  阅读: "reading book person indoor study",
  唱歌: "singing karaoke performance microphone music person",
  // Objects & scenes
  火堆: "campfire bonfire fire flame outdoor",
  篝火: "bonfire campfire fire flame night outdoor",
  码头: "dock pier harbor water boat seaside",
  灯塔: "lighthouse tower light ocean coast seaside",
  风车: "windmill wind turbine tower outdoor",
  热气球: "hot air balloon sky colorful outdoor",
  铁轨: "railroad railway train track transportation",
  隧道: "tunnel underground passage dark",
  悬崖: "cliff rock steep nature ocean landscape",
  峡谷: "canyon valley gorge rock nature landscape",
  冰山: "iceberg ice snow cold ocean polar",
  火山: "volcano mountain lava eruption nature",
  草原: "grassland prairie field meadow vast nature",
  麦田: "wheat field grain crop agriculture golden landscape",
};

// Minimum number of English keywords required for a valid translation.
// If we can't produce at least this many keywords, the query is likely
// too obscure for CLIP and we fall back to the raw Chinese text.
export const MIN_TRANSLATION_KEYWORDS = 2;
