import {
  checkGpuCapability,
  checkMirrorHealth,
  getAllAppSettings,
  getAppPreferences,
  getAppSetting,
  getDataPathInfo,
  getGpuSettings,
  getMirrorSettings,
  getOpenAtLogin,
  markGpuPromptShown,
  setAppPreference,
  setAppSetting,
  setDataPath,
  setGpuSettings,
  setMirrorSettings,
  setOpenAtLogin,
} from "./handlers";

export const settings = {
  getAllAppSettings,
  getAppPreferences,
  getAppSetting,
  setAppPreference,
  setAppSetting,
  getDataPathInfo,
  setDataPath,
  getGpuSettings,
  getMirrorSettings,
  setGpuSettings,
  setMirrorSettings,
  checkMirrorHealth,
  checkGpuCapability,
  markGpuPromptShown,
  getOpenAtLogin,
  setOpenAtLogin,
};
